# Cal.com: using Cal.com Cloud free tier (https://cal.com) instead of self-hosted.
# API key creation in the self-hosted image requires a commercial license.
# Set in .env:
#   CALCOM_API_KEY=<from cal.com Settings → Developer → API Keys>
#   CALCOM_BASE_URL=https://api.cal.com/v2
#   CALCOM_EVENT_TYPE_ID=<from event type URL>
